### ISSUE TITLE
Write and test Motor Class.

### ISSUE THREAD

**Issue by Hsenrab** [JackBuck/Robo-Plot#12]
Write a class so we can intuaitively use the motors.

This should include:
Member variables:
GPIO Pins
rps
sequence
on/off bool

Functions:
Set rps
Start()
Start(time)
Stop()
SetSequence
SetDirection()
Step()

These should all be tested.

**Comment by Hsenrab** [comment]
This class now sets up the pins and steps them forward according to the sequence. Currently the tests do not stop until the window is manually closed.

**Comment by JackBuck** [comment]
Merged in #28 but not yet reviewed

**Comment by Hsenrab** [comment]
Unfortunately I had forgotten to add the test functions so this branch has been revived and the tests added. I will look over this and check  I am happy that it is in line with the review changes Jack made before creating a pull request.

**Comment by JackBuck** [comment]
@Hsenrab Could you merge the unit tests into M_MotorFunctionality?
(Or alternatively open another pull request)

**Comment by JackBuck** [comment]
This was closed with pull request #56 and merged in 6ae8bf6ed46cbc4e45e9e8229055eb66fbfa1f7b
