### ISSUE TITLE
Design a testing process for the team

### ISSUE THREAD

**Issue by JackBuck** [JackBuck/Robo-Plot#24]
Creating this issue as I move #9 to the 'Initial project management / sysadmin' milestone.
This issue was alluded to in the old 'Process Documents' milestone but had not actually been created.

**Comment by JackBuck** [comment]
Hannah, you've already done some looking into a TDD and sourced a GPIO emulator so this feels like it best fits with you? You also wrote the description for the original milestone!

**Comment by Hsenrab** [comment]
Are we happy with this now? @JackBuck  I think we can close this issue.
