### ISSUE TITLE
Take photos with camera.

### ISSUE THREAD

**Issue by Hsenrab** [JackBuck/Robo-Plot#27]
Take photos with the camera to help us decide on the height of the camera and how far from the pen it should be.

Photos should be uploaded somewhere and linked here.

**Comment by Hsenrab** [comment]
http://raspi.tv/2013/adapt-your-raspberry-pi-camera-for-close-up-use

We may need to adapt the camera to be better at close up if we want to take close up photos in focus

**Comment by Hsenrab** [comment]
https://drive.google.com/drive/folders/0B1bLptTMLGBZNEF2aGpPUWNZQzg?usp=sharing

**Comment by JackBuck** [comment]
Ooh I forgot about focus! Though looking at the photos you took at 4 & 5 cm, they don't look too bad... The squared paper isn't too clear though!!

**Comment by Hsenrab** [comment]
I don't think the fact they are out of focus matters too much. I agree around 4-5cm is the best distance but will have to check if that is a realistic height. Are you happy I close this?

**Comment by JackBuck** [comment]
Yeah, close away :smile:
