### ISSUE TITLE
Create (debug) circuitry for plotter

### ISSUE THREAD

**Issue by LukeAWalker** [JackBuck/Robo-Plot#37]
Create a schematic and PCB with circuitry to perform the following tasks:

- Provide power to:
   - The raspberry pi
   - 5V servo motor
   - 6V stepper motor driver
   - 12V stepper motor driver

- Connectivity to:
   - (Possibly) LEDs
   - Encoders
   - Various motors

**Comment by JackBuck** [comment]
I think this is done now
