### ISSUE TITLE
Define pin/GPIO allocations for motors, LEDs, encoders, etc.

### ISSUE THREAD

**Issue by LukeAWalker** [JackBuck/Robo-Plot#38]
Define permanent allocations for the GPIO pins on the raspberry pi.

**Comment by JackBuck** [comment]
I believe that we cannot set-up GPIO pins more than once (though this may simply be the emulator warning us by raising an exception).

Do we think there is a case for some sort of `HardwareRepository` static class or module to manage handing out a singleton instance of each piece of hardware? It would also be the one piece of code responsible for hard coding the GPIO pins (hence why I'm commenting here!).

@Hsenrab

**Comment by Hsenrab** [comment]
I think that would work nicely - we cant then just call a SetupGPIOpins() function at the start of our program and know everything will be set up from then on.

**Comment by JackBuck** [comment]
I believe this is all done now.
