### ISSUE TITLE
No method RPi.GPIO.setModeDone

### ISSUE THREAD

**Issue by JackBuck** [JackBuck/Robo-Plot#40]
I will create a bugfix branch off M_MotorFunctionality to fix this.

**Comment by JackBuck** [comment]
Unfortunately I haven't managed to finish what I was doing before!
Could someone else do this please?

**Comment by JackBuck** [comment]
@Hsenrab I'm pretty sure I got it everywhere, but probably a good idea if you double check!!

**Comment by Hsenrab** [comment]
What were you trying to achieve with these commits?

**Comment by JackBuck** [comment]
The RPi.GPIO module does not define a function setModeDone() (whereas the GPIO class in the emulator does). The commits are intended to eradicate the calls to setModeDone on all the branches the bug had infected.
