### ISSUE TITLE
Create a physical test for motors.

### ISSUE THREAD

**Issue by JackBuck** [JackBuck/Robo-Plot#6]
We should be able to use it to:
- Verify the angular accuracy of the motors,
- Verify that the motion of two motor is correctly synchronised.

**Comment by JackBuck** [comment]
Printed out protractors and mounted them on card.
Attached a cocktail stick using an elastic band.

I am not sure whether the cocktail stick was moving slightly relative to the rotor (wouldn't be a problem on the small stepper since this has a flat).
I tried blutac as well but that was worse.
Does anyone have any better ideas? Or should we class this as 'good enough'?

**Comment by JackBuck** [comment]
@mrmiiike I've added you to the assignees because you were there when we used this!
I was worried about the cocktail stick moving.
Do you have any ideas? (Or ideas re anything else about it!)
If not then we might as well close this issue and leave that extra bit as a `wontfix` for now.

**Comment by mrmiiike** [comment]
I think the cocktail stick was the one of the problems, if not, the only problem of why it was slightly off. Till we find a trusted attachment method, I wouldn't worry about it too much for now. Once I get hold of a coupling, then we can test it properly for sure

**Comment by JackBuck** [comment]
Yeah, since that's something we'll have fairly soon I think we can close this for now!
