### ISSUE TITLE
Fix point discrepencies in point order passed to debug_movement.py

### ISSUE THREAD

**Issue by JackBuck** [JackBuck/Robo-Plot#69]
- Currently in all versions the `AxisPair.current_location` property is passed to `DebugImage.add_point(...)`.
- The `AxisPair.current_location` property is a point with coordinates (x,y).
- In all versions, the `DebugImage.add_point(...)` method is expecting a point ordered (y,x).

**Comment by Hsenrab** [comment]
Well spotted! Not sure how its working at all ... will look at this tonight.

**Comment by Hsenrab** [comment]
Think the way you have separated out the debugging is good much cleaner than what I had!
Need to:
Document add_point to make the x,y ordering clear.
Decide whether we are going with (y,x) or (x,y) 
Determine if it is currently working and if so why.
Fix it.

**Comment by JackBuck** [comment]
@Hsenrab Since I need this now and can't get hold of you, I'm assuming you're not currently working on this!
I'll do it now 😄

**Comment by JackBuck** [comment]
Change now merged into master, and propagated into #20 (where the svg curve is being developed ).

**Comment by Hsenrab** [comment]
Reviewed changes look fine runs as expected.
