### ISSUE TITLE
Implement pen lifting

### ISSUE THREAD

**Issue by JackBuck** [JackBuck/Robo-Plot#80]
Ideas:
  - Wrap the `AxisPair` in a `Plotter` object which also has a pen (and a camera?).
  - Create a `Pen` class with methods `raise` and `lower`, or similar. Add an instance to the `Plotter`.
  - Implement a `Plotter.draw(self, curve: Curve)` method which behaves like the current `follow` method on the `AxisPair`, but with pen control at either end.

This issue depends on #35 being completed first.

**Comment by JackBuck** [comment]
Unfortunately I have been asleep and have been committing commits for this issue under #35 .

**Comment by Hsenrab** [comment]
Yes to adding the camera object to it!

**Comment by JackBuck** [comment]
This has now been merged
